# ──────────────────────────────────────────────────────────────
# Global settings
# ──────────────────────────────────────────────────────────────

# The Lemmy instance URL and community name
instance: [https://...]
community: [community name]

# Logging & debug
log_dir: logs
debug: true              # set to false to silence DEBUG logs

# Optional filters & gating
toxicity_filter: false   # set to true to enable Detoxify filtering
max_replies: 2           # max comments/replies per scan loop
comment_roll: 70         # 1–100; bot only replies when rand ≥ this
reply_delay_min: 300   # seconds between comments (lower)
reply_delay_max: 600  # seconds between comments (upper)
initial_post: true   # ← post immediately on startup if true

# NEW: custom toxic words (any occurrence will be filtered out)
toxic_words:
  - badword 1
  - badword 2
  - badword 3 
  - badword 4

# ──────────────────────────────────────────────────────────────
# Bot definitions
# ──────────────────────────────────────────────────────────────

# name: Bot 1 # Name the bot
# model: Links to your Hugging Face (or local dir) mdoel. 
# model: Username/model # Check the URL if on Hugging Face
# username: your bots login username
# password: your bots login password
# postfreq is the number of hours a bot posts a NEW thread

bots:
  - name: Bot 1
    model: HuggingFaceUser/Model
    username: Lemmy Username
    password: Lemmy Password
    postfreq: 4
  - name: Bot 2
    model: HuggingFaceUser/Model
    username: Lemmy Username
    password: Lemmy Password
    postfreq: 4
  - name: Bot 3
    model: HuggingFaceUser/Model
    username: Lemmy Username
    password: Lemmy Password
    postfreq: 4