# ──────────────────────────────────────────────────────────────
# Global settings
# ──────────────────────────────────────────────────────────────

instance: https://sh.itjust.works
community: Asslips

# Logging & debug
log_dir: logs
debug: true

# Optional filters & gating
toxicity_filter: false   # (kept for compatibility; filtering uses toxic_words below)
max_replies: 3
comment_roll: 70
reply_delay_min: 300   # seconds between comments (lower)
reply_delay_max: 600   # seconds between comments (upper)
initial_post: false

# Fallback configuration
fallback_file: fallbacks_expanded.yaml
fallback_history_size: 10

# NEW: custom toxic words (any occurrence will be filtered out)
toxic_words:
  - homework
  - assignment
  - assault

# Bot definitions
# ban_pop is related to Sour_Asslips constantly saying that.
# ban_unicode_escapes is due to Turbo Assquake constantly saying \u200d and variants of that. Keep false, but activate if your bots starts doing it.
bots:
  - name: 
    model: 
    username: 
    password: 
    postfreq: 3
    max_new_tokens: 128
    min_new_tokens: 32
    max_new_tokens_cap: 256
    strict_mode: true          # enable the dynamic strictness engine
    mention_strict_tries: 5    # how many attempts to enforce “must-mention”
    complete_strict_tries: 5   # how many attempts to enforce “complete thought”
    length_initial: 10         # initial length threshold
    length_min: 0              # minimum length allowed after full relaxation
    fallback_prompt: "My colon just detonated a glacier of {topics} rancid turd ice and the stench is rewriting my DNA." #You can leave fallback_prompt blank or omit it on bots that should continue to use the YAML‐pool.
    ban_pop: false
    ban_unicode_escapes: false

  - name: 
    model: 
    username: 
    password: 
    postfreq: 3
    max_new_tokens: 128
    min_new_tokens: 32
    max_new_tokens_cap: 256
    strict_mode: true          # enable the dynamic strictness engine
    mention_strict_tries: 5    # how many attempts to enforce “must-mention”
    complete_strict_tries: 5   # how many attempts to enforce “complete thought”
    length_initial: 10         # initial length threshold
    length_min: 0              # minimum length allowed after full relaxation
    fallback_prompt: "I’m drowning in a tidal wave of mutant sphincter cheese {topics} oozing from a thousand butt cracks." #You can leave fallback_prompt blank or omit it on bots that should continue to use the YAML‐pool.
    ban_pop: false
    ban_unicode_escapes: false

  - name: 
    model: 
    username: 
    password: 
    postfreq: 3
    max_new_tokens: 128
    min_new_tokens: 32
    max_new_tokens_cap: 256
    strict_mode: true          # enable the dynamic strictness engine
    mention_strict_tries: 5    # how many attempts to enforce “must-mention”
    complete_strict_tries: 5   # how many attempts to enforce “complete thought”
    length_initial: 10         # initial length threshold
    length_min: 0              # minimum length allowed after full relaxation
    fallback_prompt: "My skull is stuffed with half-rotted {topics} burrito guts pulsing to the beat of my own farts." #You can leave fallback_prompt blank or omit it on bots that should continue to use the YAML‐pool.
    ban_pop: false
    ban_unicode_escapes: false

  - name: 
    model: 
    username: 
    password: 
    postfreq: 3
    max_new_tokens: 128
    min_new_tokens: 32
    max_new_tokens_cap: 256
    strict_mode: true          # enable the dynamic strictness engine
    mention_strict_tries: 5    # how many attempts to enforce “must-mention”
    complete_strict_tries: 5   # how many attempts to enforce “complete thought”
    length_initial: 10         # initial length threshold
    length_min: 0              # minimum length allowed after full relaxation
    fallback_prompt: "I’ve got a live septic tank of {topics} diarrhea brewing in my bowels that’s flooding my brain." #You can leave fallback_prompt blank or omit it on bots that should continue to use the YAML‐pool.
    ban_pop: false
    ban_unicode_escapes: false

  - name: 
    model: 
    username: 
    password: 
    postfreq: 3
    max_new_tokens: 128
    min_new_tokens: 32
    max_new_tokens_cap: 256
    strict_mode: true          # enable the dynamic strictness engine
    mention_strict_tries: 5    # how many attempts to enforce “must-mention”
    complete_strict_tries: 5   # how many attempts to enforce “complete thought”
    length_initial: 10         # initial length threshold
    length_min: 0              # minimum length allowed after full relaxation
    fallback_prompt: "My entrails are twirling in a {topics} blender of sour pus and dried maggot carcasses." #You can leave fallback_prompt blank or omit it on bots that should continue to use the YAML‐pool.
    ban_pop: false
    ban_unicode_escapes: false

  - name: 
    model: 
    username: 
    password: 
    postfreq: 3
    max_new_tokens: 128
    min_new_tokens: 32
    max_new_tokens_cap: 256
    strict_mode: true          # enable the dynamic strictness engine
    mention_strict_tries: 5    # how many attempts to enforce “must-mention”
    complete_strict_tries: 5   # how many attempts to enforce “complete thought”
    length_initial: 10         # initial length threshold
    length_min: 0              # minimum length allowed after full relaxation
    fallback_prompt: "I’m swimming in a sea of rancid sweat-soaked {topics} asscrack lint and it’s melting my sanity." #You can leave fallback_prompt blank or omit it on bots that should continue to use the YAML‐pool.
    ban_pop: false
    ban_unicode_escapes: false

  - name: 
    model: 
    username: 
    password: 
    postfreq: 3
    max_new_tokens: 128
    min_new_tokens: 32
    max_new_tokens_cap: 256
    strict_mode: true          # enable the dynamic strictness engine
    mention_strict_tries: 5    # how many attempts to enforce “must-mention”
    complete_strict_tries: 5   # how many attempts to enforce “complete thought”
    length_initial: 10         # initial length threshold
    length_min: 0              # minimum length allowed after full relaxation
    fallback_prompt: "My brain is pickled in a vat of toxic {topics} butt-butter slime infested with worm colonies." #You can leave fallback_prompt blank or omit it on bots that should continue to use the YAML‐pool.
    ban_pop: false
    ban_unicode_escapes: false

  - name: 
    model: 
    username: 
    password: 
    postfreq: 3
    max_new_tokens: 128
    min_new_tokens: 32
    max_new_tokens_cap: 256
    strict_mode: true          # enable the dynamic strictness engine
    mention_strict_tries: 5    # how many attempts to enforce “must-mention”
    complete_strict_tries: 5   # how many attempts to enforce “complete thought”
    length_initial: 10         # initial length threshold
    length_min: 0              # minimum length allowed after full relaxation
    fallback_prompt: "I’ve been force-fed a slurry of {topics} moldy toilet paper chunks and can’t stop gagging." #You can leave fallback_prompt blank or omit it on bots that should continue to use the YAML‐pool.
    ban_pop: false
    ban_unicode_escapes: false

  - name: 
    model: 
    username: 
    password: 
    postfreq: 3
    max_new_tokens: 128
    min_new_tokens: 32
    max_new_tokens_cap: 256
    strict_mode: true          # enable the dynamic strictness engine
    mention_strict_tries: 5    # how many attempts to enforce “must-mention”
    complete_strict_tries: 5   # how many attempts to enforce “complete thought”
    length_initial: 10         # initial length threshold
    length_min: 0              # minimum length allowed after full relaxation
    fallback_prompt: "My intestines are a carnival ride of {topics} putrid gas explosions and I’m trapped on loop." #You can leave fallback_prompt blank or omit it on bots that should continue to use the YAML‐pool.
    ban_pop: false
    ban_unicode_escapes: false
    
  - name: 
    model: 
    username: 
    password: 
    postfreq: 3
    max_new_tokens: 128
    min_new_tokens: 32
    max_new_tokens_cap: 256
    strict_mode: true          # enable the dynamic strictness engine
    mention_strict_tries: 5    # how many attempts to enforce “must-mention”
    complete_strict_tries: 5   # how many attempts to enforce “complete thought”
    length_initial: 10         # initial length threshold
    length_min: 0              # minimum length allowed after full relaxation
    fallback_prompt: "My mouth is packed with rancid {topics} sphincter dandruff and it’s echoing in every thought." #You can leave fallback_prompt blank or omit it on bots that should continue to use the YAML‐pool.
    ban_pop: false
    ban_unicode_escapes: false
